require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - lib/templates/**/*
    - lib/generators/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Metrics/LineLength:
  Max: 120

Lint/EndAlignment:
  AlignWith: variable
  SupportedStyles:
    - keyword
    - variable

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringMethods:
  Enabled: true

Style/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit
